# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatbuf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chatbuf.proto',
  package='SyncDemo',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rchatbuf.proto\x12\x08SyncDemo\"\x90\x02\n\x0b\x43hatMessage\x12\n\n\x02to\x18\x01 \x02(\t\x12\x0c\n\x04\x66rom\x18\x02 \x02(\t\x12\x39\n\x04type\x18\x03 \x02(\x0e\x32%.SyncDemo.ChatMessage.ChatMessageType:\x04\x43HAT\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\t\x12\x11\n\tmediadata\x18\x05 \x01(\x0c\x12\x11\n\ttimestamp\x18\x06 \x02(\x05\x12\x12\n\nfinalblock\x18\x07 \x01(\x05\x12\x11\n\tmedianame\x18\x08 \x01(\t\"Q\n\x0f\x43hatMessageType\x12\x08\n\x04\x43HAT\x10\x00\x12\t\n\x05HELLO\x10\x01\x12\t\n\x05LEAVE\x10\x02\x12\x08\n\x04JOIN\x10\x03\x12\t\n\x05OTHER\x10\x04\x12\t\n\x05MEDIA\x10\x05')
)



_CHATMESSAGE_CHATMESSAGETYPE = _descriptor.EnumDescriptor(
  name='ChatMessageType',
  full_name='SyncDemo.ChatMessage.ChatMessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CHAT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HELLO', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEAVE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JOIN', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MEDIA', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=219,
  serialized_end=300,
)
_sym_db.RegisterEnumDescriptor(_CHATMESSAGE_CHATMESSAGETYPE)


_CHATMESSAGE = _descriptor.Descriptor(
  name='ChatMessage',
  full_name='SyncDemo.ChatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='to', full_name='SyncDemo.ChatMessage.to', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='from', full_name='SyncDemo.ChatMessage.from', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='SyncDemo.ChatMessage.type', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='SyncDemo.ChatMessage.data', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mediadata', full_name='SyncDemo.ChatMessage.mediadata', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='SyncDemo.ChatMessage.timestamp', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='finalblock', full_name='SyncDemo.ChatMessage.finalblock', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='medianame', full_name='SyncDemo.ChatMessage.medianame', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CHATMESSAGE_CHATMESSAGETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=300,
)

_CHATMESSAGE.fields_by_name['type'].enum_type = _CHATMESSAGE_CHATMESSAGETYPE
_CHATMESSAGE_CHATMESSAGETYPE.containing_type = _CHATMESSAGE
DESCRIPTOR.message_types_by_name['ChatMessage'] = _CHATMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChatMessage = _reflection.GeneratedProtocolMessageType('ChatMessage', (_message.Message,), {
  'DESCRIPTOR' : _CHATMESSAGE,
  '__module__' : 'chatbuf_pb2'
  # @@protoc_insertion_point(class_scope:SyncDemo.ChatMessage)
  })
_sym_db.RegisterMessage(ChatMessage)


# @@protoc_insertion_point(module_scope)
